# Generated by Django 3.1.7 on 2021-04-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
